/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdminCreateNestedManyWithoutBookingsInput } from "./AdminCreateNestedManyWithoutBookingsInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ServiceCategoryWhereUniqueInput } from "../../serviceCategory/base/ServiceCategoryWhereUniqueInput";
import { ServiceProviderWhereUniqueInput } from "../../serviceProvider/base/ServiceProviderWhereUniqueInput";
import { ServiceProviderCreateNestedManyWithoutBookingsInput } from "./ServiceProviderCreateNestedManyWithoutBookingsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class BookingCreateInput {
  @ApiProperty({
    required: false,
    type: () => AdminCreateNestedManyWithoutBookingsInput,
  })
  @ValidateNested()
  @Type(() => AdminCreateNestedManyWithoutBookingsInput)
  @IsOptional()
  @Field(() => AdminCreateNestedManyWithoutBookingsInput, {
    nullable: true,
  })
  admins?: AdminCreateNestedManyWithoutBookingsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  bookingDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  paymentStatus?: string | null;

  @ApiProperty({
    required: false,
    type: () => ServiceCategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServiceCategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => ServiceCategoryWhereUniqueInput, {
    nullable: true,
  })
  serviceCategory?: ServiceCategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ServiceProviderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServiceProviderWhereUniqueInput)
  @IsOptional()
  @Field(() => ServiceProviderWhereUniqueInput, {
    nullable: true,
  })
  serviceProvider?: ServiceProviderWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ServiceProviderCreateNestedManyWithoutBookingsInput,
  })
  @ValidateNested()
  @Type(() => ServiceProviderCreateNestedManyWithoutBookingsInput)
  @IsOptional()
  @Field(() => ServiceProviderCreateNestedManyWithoutBookingsInput, {
    nullable: true,
  })
  serviceProviders?: ServiceProviderCreateNestedManyWithoutBookingsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { BookingCreateInput as BookingCreateInput };
