/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Admin } from "../../admin/base/Admin";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ServiceCategory } from "../../serviceCategory/base/ServiceCategory";
import { ServiceProvider } from "../../serviceProvider/base/ServiceProvider";
import { User } from "../../user/base/User";

@ObjectType()
class Booking {
  @ApiProperty({
    required: false,
    type: () => [Admin],
  })
  @ValidateNested()
  @Type(() => Admin)
  @IsOptional()
  admins?: Array<Admin>;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  bookingDate!: Date | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  paymentStatus!: string | null;

  @ApiProperty({
    required: false,
    type: () => ServiceCategory,
  })
  @ValidateNested()
  @Type(() => ServiceCategory)
  @IsOptional()
  serviceCategory?: ServiceCategory | null;

  @ApiProperty({
    required: false,
    type: () => ServiceProvider,
  })
  @ValidateNested()
  @Type(() => ServiceProvider)
  @IsOptional()
  serviceProvider?: ServiceProvider | null;

  @ApiProperty({
    required: false,
    type: () => [ServiceProvider],
  })
  @ValidateNested()
  @Type(() => ServiceProvider)
  @IsOptional()
  serviceProviders?: Array<ServiceProvider>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  user?: User | null;
}

export { Booking as Booking };
