/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdminCreateNestedManyWithoutReviewsInput } from "./AdminCreateNestedManyWithoutReviewsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsInt,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { ServiceProviderWhereUniqueInput } from "../../serviceProvider/base/ServiceProviderWhereUniqueInput";
import { ServiceProviderCreateNestedManyWithoutReviewsInput } from "./ServiceProviderCreateNestedManyWithoutReviewsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ReviewCreateInput {
  @ApiProperty({
    required: false,
    type: () => AdminCreateNestedManyWithoutReviewsInput,
  })
  @ValidateNested()
  @Type(() => AdminCreateNestedManyWithoutReviewsInput)
  @IsOptional()
  @Field(() => AdminCreateNestedManyWithoutReviewsInput, {
    nullable: true,
  })
  admins?: AdminCreateNestedManyWithoutReviewsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  comment?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rating?: number | null;

  @ApiProperty({
    required: false,
    type: () => ServiceProviderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServiceProviderWhereUniqueInput)
  @IsOptional()
  @Field(() => ServiceProviderWhereUniqueInput, {
    nullable: true,
  })
  serviceProvider?: ServiceProviderWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ServiceProviderCreateNestedManyWithoutReviewsInput,
  })
  @ValidateNested()
  @Type(() => ServiceProviderCreateNestedManyWithoutReviewsInput)
  @IsOptional()
  @Field(() => ServiceProviderCreateNestedManyWithoutReviewsInput, {
    nullable: true,
  })
  serviceProviders?: ServiceProviderCreateNestedManyWithoutReviewsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ReviewCreateInput as ReviewCreateInput };
