/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdminListRelationFilter } from "../../admin/base/AdminListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { ServiceProviderWhereUniqueInput } from "../../serviceProvider/base/ServiceProviderWhereUniqueInput";
import { ServiceProviderListRelationFilter } from "../../serviceProvider/base/ServiceProviderListRelationFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ReviewWhereInput {
  @ApiProperty({
    required: false,
    type: () => AdminListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AdminListRelationFilter)
  @IsOptional()
  @Field(() => AdminListRelationFilter, {
    nullable: true,
  })
  admins?: AdminListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  comment?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  rating?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ServiceProviderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServiceProviderWhereUniqueInput)
  @IsOptional()
  @Field(() => ServiceProviderWhereUniqueInput, {
    nullable: true,
  })
  serviceProvider?: ServiceProviderWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ServiceProviderListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ServiceProviderListRelationFilter)
  @IsOptional()
  @Field(() => ServiceProviderListRelationFilter, {
    nullable: true,
  })
  serviceProviders?: ServiceProviderListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { ReviewWhereInput as ReviewWhereInput };
