/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ServiceProvider } from "./ServiceProvider";
import { ServiceProviderCountArgs } from "./ServiceProviderCountArgs";
import { ServiceProviderFindManyArgs } from "./ServiceProviderFindManyArgs";
import { ServiceProviderFindUniqueArgs } from "./ServiceProviderFindUniqueArgs";
import { CreateServiceProviderArgs } from "./CreateServiceProviderArgs";
import { UpdateServiceProviderArgs } from "./UpdateServiceProviderArgs";
import { DeleteServiceProviderArgs } from "./DeleteServiceProviderArgs";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { ReviewFindManyArgs } from "../../review/base/ReviewFindManyArgs";
import { Review } from "../../review/base/Review";
import { ServiceCategoryFindManyArgs } from "../../serviceCategory/base/ServiceCategoryFindManyArgs";
import { ServiceCategory } from "../../serviceCategory/base/ServiceCategory";
import { ServiceProviderService } from "../serviceProvider.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ServiceProvider)
export class ServiceProviderResolverBase {
  constructor(
    protected readonly service: ServiceProviderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "read",
    possession: "any",
  })
  async _serviceProvidersMeta(
    @graphql.Args() args: ServiceProviderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ServiceProvider])
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "read",
    possession: "any",
  })
  async serviceProviders(
    @graphql.Args() args: ServiceProviderFindManyArgs
  ): Promise<ServiceProvider[]> {
    return this.service.serviceProviders(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ServiceProvider, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "read",
    possession: "own",
  })
  async serviceProvider(
    @graphql.Args() args: ServiceProviderFindUniqueArgs
  ): Promise<ServiceProvider | null> {
    const result = await this.service.serviceProvider(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ServiceProvider)
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "create",
    possession: "any",
  })
  async createServiceProvider(
    @graphql.Args() args: CreateServiceProviderArgs
  ): Promise<ServiceProvider> {
    return await this.service.createServiceProvider({
      ...args,
      data: {
        ...args.data,

        booking: args.data.booking
          ? {
              connect: args.data.booking,
            }
          : undefined,

        review: args.data.review
          ? {
              connect: args.data.review,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ServiceProvider)
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  async updateServiceProvider(
    @graphql.Args() args: UpdateServiceProviderArgs
  ): Promise<ServiceProvider | null> {
    try {
      return await this.service.updateServiceProvider({
        ...args,
        data: {
          ...args.data,

          booking: args.data.booking
            ? {
                connect: args.data.booking,
              }
            : undefined,

          review: args.data.review
            ? {
                connect: args.data.review,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ServiceProvider)
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "delete",
    possession: "any",
  })
  async deleteServiceProvider(
    @graphql.Args() args: DeleteServiceProviderArgs
  ): Promise<ServiceProvider | null> {
    try {
      return await this.service.deleteServiceProvider(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Booking], { name: "bookings" })
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async findBookings(
    @graphql.Parent() parent: ServiceProvider,
    @graphql.Args() args: BookingFindManyArgs
  ): Promise<Booking[]> {
    const results = await this.service.findBookings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Review], { name: "reviews" })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  async findReviews(
    @graphql.Parent() parent: ServiceProvider,
    @graphql.Args() args: ReviewFindManyArgs
  ): Promise<Review[]> {
    const results = await this.service.findReviews(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ServiceCategory], { name: "serviceCategories" })
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "read",
    possession: "any",
  })
  async findServiceCategories(
    @graphql.Parent() parent: ServiceProvider,
    @graphql.Args() args: ServiceCategoryFindManyArgs
  ): Promise<ServiceCategory[]> {
    const results = await this.service.findServiceCategories(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Booking, {
    nullable: true,
    name: "booking",
  })
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async getBooking(
    @graphql.Parent() parent: ServiceProvider
  ): Promise<Booking | null> {
    const result = await this.service.getBooking(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Review, {
    nullable: true,
    name: "review",
  })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  async getReview(
    @graphql.Parent() parent: ServiceProvider
  ): Promise<Review | null> {
    const result = await this.service.getReview(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
