/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ServiceProviderService } from "../serviceProvider.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ServiceProviderCreateInput } from "./ServiceProviderCreateInput";
import { ServiceProvider } from "./ServiceProvider";
import { ServiceProviderFindManyArgs } from "./ServiceProviderFindManyArgs";
import { ServiceProviderWhereUniqueInput } from "./ServiceProviderWhereUniqueInput";
import { ServiceProviderUpdateInput } from "./ServiceProviderUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";
import { ReviewFindManyArgs } from "../../review/base/ReviewFindManyArgs";
import { Review } from "../../review/base/Review";
import { ReviewWhereUniqueInput } from "../../review/base/ReviewWhereUniqueInput";
import { ServiceCategoryFindManyArgs } from "../../serviceCategory/base/ServiceCategoryFindManyArgs";
import { ServiceCategory } from "../../serviceCategory/base/ServiceCategory";
import { ServiceCategoryWhereUniqueInput } from "../../serviceCategory/base/ServiceCategoryWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ServiceProviderControllerBase {
  constructor(
    protected readonly service: ServiceProviderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ServiceProvider })
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createServiceProvider(
    @common.Body() data: ServiceProviderCreateInput
  ): Promise<ServiceProvider> {
    return await this.service.createServiceProvider({
      data: {
        ...data,

        booking: data.booking
          ? {
              connect: data.booking,
            }
          : undefined,

        review: data.review
          ? {
              connect: data.review,
            }
          : undefined,
      },
      select: {
        availability: true,
        bio: true,

        booking: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        hourlyRate: true,
        id: true,
        name: true,
        phone: true,
        ratings: true,

        review: {
          select: {
            id: true,
          },
        },

        serviceType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ServiceProvider] })
  @ApiNestedQuery(ServiceProviderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceProviders(
    @common.Req() request: Request
  ): Promise<ServiceProvider[]> {
    const args = plainToClass(ServiceProviderFindManyArgs, request.query);
    return this.service.serviceProviders({
      ...args,
      select: {
        availability: true,
        bio: true,

        booking: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        hourlyRate: true,
        id: true,
        name: true,
        phone: true,
        ratings: true,

        review: {
          select: {
            id: true,
          },
        },

        serviceType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ServiceProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceProvider(
    @common.Param() params: ServiceProviderWhereUniqueInput
  ): Promise<ServiceProvider | null> {
    const result = await this.service.serviceProvider({
      where: params,
      select: {
        availability: true,
        bio: true,

        booking: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        hourlyRate: true,
        id: true,
        name: true,
        phone: true,
        ratings: true,

        review: {
          select: {
            id: true,
          },
        },

        serviceType: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ServiceProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateServiceProvider(
    @common.Param() params: ServiceProviderWhereUniqueInput,
    @common.Body() data: ServiceProviderUpdateInput
  ): Promise<ServiceProvider | null> {
    try {
      return await this.service.updateServiceProvider({
        where: params,
        data: {
          ...data,

          booking: data.booking
            ? {
                connect: data.booking,
              }
            : undefined,

          review: data.review
            ? {
                connect: data.review,
              }
            : undefined,
        },
        select: {
          availability: true,
          bio: true,

          booking: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          hourlyRate: true,
          id: true,
          name: true,
          phone: true,
          ratings: true,

          review: {
            select: {
              id: true,
            },
          },

          serviceType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ServiceProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteServiceProvider(
    @common.Param() params: ServiceProviderWhereUniqueInput
  ): Promise<ServiceProvider | null> {
    try {
      return await this.service.deleteServiceProvider({
        where: params,
        select: {
          availability: true,
          bio: true,

          booking: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          hourlyRate: true,
          id: true,
          name: true,
          phone: true,
          ratings: true,

          review: {
            select: {
              id: true,
            },
          },

          serviceType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: ServiceProviderWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        bookingDate: true,
        createdAt: true,
        id: true,
        paymentStatus: true,

        serviceCategory: {
          select: {
            id: true,
          },
        },

        serviceProvider: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  async connectBookings(
    @common.Param() params: ServiceProviderWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateServiceProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  async updateBookings(
    @common.Param() params: ServiceProviderWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateServiceProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  async disconnectBookings(
    @common.Param() params: ServiceProviderWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateServiceProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/reviews")
  @ApiNestedQuery(ReviewFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  async findReviews(
    @common.Req() request: Request,
    @common.Param() params: ServiceProviderWhereUniqueInput
  ): Promise<Review[]> {
    const query = plainToClass(ReviewFindManyArgs, request.query);
    const results = await this.service.findReviews(params.id, {
      ...query,
      select: {
        comment: true,
        createdAt: true,
        id: true,
        rating: true,

        serviceProvider: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reviews")
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  async connectReviews(
    @common.Param() params: ServiceProviderWhereUniqueInput,
    @common.Body() body: ReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviews: {
        connect: body,
      },
    };
    await this.service.updateServiceProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reviews")
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  async updateReviews(
    @common.Param() params: ServiceProviderWhereUniqueInput,
    @common.Body() body: ReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviews: {
        set: body,
      },
    };
    await this.service.updateServiceProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reviews")
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  async disconnectReviews(
    @common.Param() params: ServiceProviderWhereUniqueInput,
    @common.Body() body: ReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviews: {
        disconnect: body,
      },
    };
    await this.service.updateServiceProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/serviceCategories")
  @ApiNestedQuery(ServiceCategoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "read",
    possession: "any",
  })
  async findServiceCategories(
    @common.Req() request: Request,
    @common.Param() params: ServiceProviderWhereUniqueInput
  ): Promise<ServiceCategory[]> {
    const query = plainToClass(ServiceCategoryFindManyArgs, request.query);
    const results = await this.service.findServiceCategories(params.id, {
      ...query,
      select: {
        categoryName: true,
        createdAt: true,
        description: true,
        id: true,

        serviceProvider: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/serviceCategories")
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  async connectServiceCategories(
    @common.Param() params: ServiceProviderWhereUniqueInput,
    @common.Body() body: ServiceCategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      serviceCategories: {
        connect: body,
      },
    };
    await this.service.updateServiceProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/serviceCategories")
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  async updateServiceCategories(
    @common.Param() params: ServiceProviderWhereUniqueInput,
    @common.Body() body: ServiceCategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      serviceCategories: {
        set: body,
      },
    };
    await this.service.updateServiceProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/serviceCategories")
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "update",
    possession: "any",
  })
  async disconnectServiceCategories(
    @common.Param() params: ServiceProviderWhereUniqueInput,
    @common.Body() body: ServiceCategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      serviceCategories: {
        disconnect: body,
      },
    };
    await this.service.updateServiceProvider({
      where: params,
      data,
      select: { id: true },
    });
  }
}
