/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsNumber,
  Min,
  Max,
} from "class-validator";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";
import { Type } from "class-transformer";
import { BookingUpdateManyWithoutServiceProvidersInput } from "./BookingUpdateManyWithoutServiceProvidersInput";
import { ReviewWhereUniqueInput } from "../../review/base/ReviewWhereUniqueInput";
import { ReviewUpdateManyWithoutServiceProvidersInput } from "./ReviewUpdateManyWithoutServiceProvidersInput";
import { ServiceCategoryUpdateManyWithoutServiceProvidersInput } from "./ServiceCategoryUpdateManyWithoutServiceProvidersInput";

@InputType()
class ServiceProviderUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  availability?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
    type: () => BookingWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BookingWhereUniqueInput)
  @IsOptional()
  @Field(() => BookingWhereUniqueInput, {
    nullable: true,
  })
  booking?: BookingWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => BookingUpdateManyWithoutServiceProvidersInput,
  })
  @ValidateNested()
  @Type(() => BookingUpdateManyWithoutServiceProvidersInput)
  @IsOptional()
  @Field(() => BookingUpdateManyWithoutServiceProvidersInput, {
    nullable: true,
  })
  bookings?: BookingUpdateManyWithoutServiceProvidersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  hourlyRate?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ratings?: string | null;

  @ApiProperty({
    required: false,
    type: () => ReviewWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ReviewWhereUniqueInput)
  @IsOptional()
  @Field(() => ReviewWhereUniqueInput, {
    nullable: true,
  })
  review?: ReviewWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReviewUpdateManyWithoutServiceProvidersInput,
  })
  @ValidateNested()
  @Type(() => ReviewUpdateManyWithoutServiceProvidersInput)
  @IsOptional()
  @Field(() => ReviewUpdateManyWithoutServiceProvidersInput, {
    nullable: true,
  })
  reviews?: ReviewUpdateManyWithoutServiceProvidersInput;

  @ApiProperty({
    required: false,
    type: () => ServiceCategoryUpdateManyWithoutServiceProvidersInput,
  })
  @ValidateNested()
  @Type(() => ServiceCategoryUpdateManyWithoutServiceProvidersInput)
  @IsOptional()
  @Field(() => ServiceCategoryUpdateManyWithoutServiceProvidersInput, {
    nullable: true,
  })
  serviceCategories?: ServiceCategoryUpdateManyWithoutServiceProvidersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  serviceType?: string | null;
}

export { ServiceProviderUpdateInput as ServiceProviderUpdateInput };
