/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ServiceCategoryService } from "../serviceCategory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ServiceCategoryCreateInput } from "./ServiceCategoryCreateInput";
import { ServiceCategory } from "./ServiceCategory";
import { ServiceCategoryFindManyArgs } from "./ServiceCategoryFindManyArgs";
import { ServiceCategoryWhereUniqueInput } from "./ServiceCategoryWhereUniqueInput";
import { ServiceCategoryUpdateInput } from "./ServiceCategoryUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ServiceCategoryControllerBase {
  constructor(
    protected readonly service: ServiceCategoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ServiceCategory })
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createServiceCategory(
    @common.Body() data: ServiceCategoryCreateInput
  ): Promise<ServiceCategory> {
    return await this.service.createServiceCategory({
      data: {
        ...data,

        serviceProvider: data.serviceProvider
          ? {
              connect: data.serviceProvider,
            }
          : undefined,
      },
      select: {
        categoryName: true,
        createdAt: true,
        description: true,
        id: true,

        serviceProvider: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ServiceCategory] })
  @ApiNestedQuery(ServiceCategoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceCategories(
    @common.Req() request: Request
  ): Promise<ServiceCategory[]> {
    const args = plainToClass(ServiceCategoryFindManyArgs, request.query);
    return this.service.serviceCategories({
      ...args,
      select: {
        categoryName: true,
        createdAt: true,
        description: true,
        id: true,

        serviceProvider: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ServiceCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceCategory(
    @common.Param() params: ServiceCategoryWhereUniqueInput
  ): Promise<ServiceCategory | null> {
    const result = await this.service.serviceCategory({
      where: params,
      select: {
        categoryName: true,
        createdAt: true,
        description: true,
        id: true,

        serviceProvider: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ServiceCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateServiceCategory(
    @common.Param() params: ServiceCategoryWhereUniqueInput,
    @common.Body() data: ServiceCategoryUpdateInput
  ): Promise<ServiceCategory | null> {
    try {
      return await this.service.updateServiceCategory({
        where: params,
        data: {
          ...data,

          serviceProvider: data.serviceProvider
            ? {
                connect: data.serviceProvider,
              }
            : undefined,
        },
        select: {
          categoryName: true,
          createdAt: true,
          description: true,
          id: true,

          serviceProvider: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ServiceCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteServiceCategory(
    @common.Param() params: ServiceCategoryWhereUniqueInput
  ): Promise<ServiceCategory | null> {
    try {
      return await this.service.deleteServiceCategory({
        where: params,
        select: {
          categoryName: true,
          createdAt: true,
          description: true,
          id: true,

          serviceProvider: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: ServiceCategoryWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        bookingDate: true,
        createdAt: true,
        id: true,
        paymentStatus: true,

        serviceCategory: {
          select: {
            id: true,
          },
        },

        serviceProvider: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "update",
    possession: "any",
  })
  async connectBookings(
    @common.Param() params: ServiceCategoryWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateServiceCategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "update",
    possession: "any",
  })
  async updateBookings(
    @common.Param() params: ServiceCategoryWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateServiceCategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "update",
    possession: "any",
  })
  async disconnectBookings(
    @common.Param() params: ServiceCategoryWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateServiceCategory({
      where: params,
      data,
      select: { id: true },
    });
  }
}
