/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ServiceCategory as PrismaServiceCategory,
  Booking as PrismaBooking,
  ServiceProvider as PrismaServiceProvider,
} from "@prisma/client";

export class ServiceCategoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ServiceCategoryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.serviceCategory.count(args);
  }

  async serviceCategories(
    args: Prisma.ServiceCategoryFindManyArgs
  ): Promise<PrismaServiceCategory[]> {
    return this.prisma.serviceCategory.findMany(args);
  }
  async serviceCategory(
    args: Prisma.ServiceCategoryFindUniqueArgs
  ): Promise<PrismaServiceCategory | null> {
    return this.prisma.serviceCategory.findUnique(args);
  }
  async createServiceCategory(
    args: Prisma.ServiceCategoryCreateArgs
  ): Promise<PrismaServiceCategory> {
    return this.prisma.serviceCategory.create(args);
  }
  async updateServiceCategory(
    args: Prisma.ServiceCategoryUpdateArgs
  ): Promise<PrismaServiceCategory> {
    return this.prisma.serviceCategory.update(args);
  }
  async deleteServiceCategory(
    args: Prisma.ServiceCategoryDeleteArgs
  ): Promise<PrismaServiceCategory> {
    return this.prisma.serviceCategory.delete(args);
  }

  async findBookings(
    parentId: string,
    args: Prisma.BookingFindManyArgs
  ): Promise<PrismaBooking[]> {
    return this.prisma.serviceCategory
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .bookings(args);
  }

  async getServiceProvider(
    parentId: string
  ): Promise<PrismaServiceProvider | null> {
    return this.prisma.serviceCategory
      .findUnique({
        where: { id: parentId },
      })
      .serviceProvider();
  }
}
