/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ServiceCategory } from "./ServiceCategory";
import { ServiceCategoryCountArgs } from "./ServiceCategoryCountArgs";
import { ServiceCategoryFindManyArgs } from "./ServiceCategoryFindManyArgs";
import { ServiceCategoryFindUniqueArgs } from "./ServiceCategoryFindUniqueArgs";
import { CreateServiceCategoryArgs } from "./CreateServiceCategoryArgs";
import { UpdateServiceCategoryArgs } from "./UpdateServiceCategoryArgs";
import { DeleteServiceCategoryArgs } from "./DeleteServiceCategoryArgs";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { ServiceProvider } from "../../serviceProvider/base/ServiceProvider";
import { ServiceCategoryService } from "../serviceCategory.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ServiceCategory)
export class ServiceCategoryResolverBase {
  constructor(
    protected readonly service: ServiceCategoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "read",
    possession: "any",
  })
  async _serviceCategoriesMeta(
    @graphql.Args() args: ServiceCategoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ServiceCategory])
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "read",
    possession: "any",
  })
  async serviceCategories(
    @graphql.Args() args: ServiceCategoryFindManyArgs
  ): Promise<ServiceCategory[]> {
    return this.service.serviceCategories(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ServiceCategory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "read",
    possession: "own",
  })
  async serviceCategory(
    @graphql.Args() args: ServiceCategoryFindUniqueArgs
  ): Promise<ServiceCategory | null> {
    const result = await this.service.serviceCategory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ServiceCategory)
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "create",
    possession: "any",
  })
  async createServiceCategory(
    @graphql.Args() args: CreateServiceCategoryArgs
  ): Promise<ServiceCategory> {
    return await this.service.createServiceCategory({
      ...args,
      data: {
        ...args.data,

        serviceProvider: args.data.serviceProvider
          ? {
              connect: args.data.serviceProvider,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ServiceCategory)
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "update",
    possession: "any",
  })
  async updateServiceCategory(
    @graphql.Args() args: UpdateServiceCategoryArgs
  ): Promise<ServiceCategory | null> {
    try {
      return await this.service.updateServiceCategory({
        ...args,
        data: {
          ...args.data,

          serviceProvider: args.data.serviceProvider
            ? {
                connect: args.data.serviceProvider,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ServiceCategory)
  @nestAccessControl.UseRoles({
    resource: "ServiceCategory",
    action: "delete",
    possession: "any",
  })
  async deleteServiceCategory(
    @graphql.Args() args: DeleteServiceCategoryArgs
  ): Promise<ServiceCategory | null> {
    try {
      return await this.service.deleteServiceCategory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Booking], { name: "bookings" })
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async findBookings(
    @graphql.Parent() parent: ServiceCategory,
    @graphql.Args() args: BookingFindManyArgs
  ): Promise<Booking[]> {
    const results = await this.service.findBookings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => ServiceProvider, {
    nullable: true,
    name: "serviceProvider",
  })
  @nestAccessControl.UseRoles({
    resource: "ServiceProvider",
    action: "read",
    possession: "any",
  })
  async getServiceProvider(
    @graphql.Parent() parent: ServiceCategory
  ): Promise<ServiceProvider | null> {
    const result = await this.service.getServiceProvider(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
